require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'yogiyogi' do

  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"


  use_react_native!(:path => config["reactNativePath"])

  target 'yogiyogiTests' do
    inherit! :complete
    # Pods for testing
  end
    # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end



  

end
target 'yogiyogi-tvOS' do
  # Pods for yogiyogi-tvOS
  target 'yogiyogi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal'
end


# Post Install processing for Flipper
# def flipper_post_install(installer)
#   installer.pods_project.targets.each do |target|
#     if target.name == 'YogaKit'
#       target.build_configurations.each do |config|
#         config.build_settings['SWIFT_VERSION'] = '4.1'
#         if config.name == 'Debug'
#           config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
#           # config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
#         end
#       end
#     end
#   end
#   file_name = Dir.glob("*.xcodeproj")[0]
#   app_project = Xcodeproj::Project.open(file_name)
#   app_project.native_targets.each do |target|
#     target.build_configurations.each do |config|
#       cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
#       unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
#         puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
#         cflags << '-DFB_SONARKIT_ENABLED=1'
#       end
#       config.build_settings['OTHER_CFLAGS'] = cflags
#     end
#     app_project.save
#   end
#   installer.pods_project.save
# end
